In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
pip install kagglehub

Defaulting to user installation because normal site-packages is not writeable
     -------------------------------------- 70.6/70.6 kB 642.5 kB/s eta 0:00:00
     ------------------------------------ 160.4/160.4 kB 685.5 kB/s eta 0:00:00
     -------------------------------------- 78.4/78.4 kB 619.4 kB/s eta 0:00:00
     ------------------------------------ 437.1/437.1 kB 882.0 kB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip available: 22.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
import kagglehub as kb
print("its working")

its working


In [7]:
pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [8]:
import sklearn as sk
print("i")

i


In [54]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import os
import kagglehub as kb
path = kb.dataset_download("abdulwadood11220/netflix-customer-churn-dataset")
print("the path of dataset files",path)
files = os.listdir(path)
print("files downloaded",files)
df=pd.read_csv("C:\\Users\\Ammar Shaikh\\.cache\\kagglehub\\datasets\\abdulwadood11220\\netflix-customer-churn-dataset\\versions\\1\\netflix_customer_churn.csv")
df.info()
df.shape
df.head()
df.describe(include='all').T


the path of dataset files C:\Users\Ammar Shaikh\.cache\kagglehub\datasets\abdulwadood11220\netflix-customer-churn-dataset\versions\1
files downloaded ['netflix_customer_churn.csv']
<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   customer_id             5000 non-null   str    
 1   age                     5000 non-null   int64  
 2   gender                  5000 non-null   str    
 3   subscription_type       5000 non-null   str    
 4   watch_hours             5000 non-null   float64
 5   last_login_days         5000 non-null   int64  
 6   region                  5000 non-null   str    
 7   device                  5000 non-null   str    
 8   monthly_fee             5000 non-null   float64
 9   churned                 5000 non-null   int64  
 10  payment_method          5000 non-null   str    
 11  number_of_profiles      5000 

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
customer_id,5000,5000,a9b75100-82a8-427a-a208-72f24052884a,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
age,5000.0,NaN,NaN,NaN,43.8474,15.501128,18.0,30.0,44.0,58.0,70.0
gender,5000,3,Female,1711,NaN,NaN,NaN,NaN,NaN,NaN,NaN
subscription_type,5000,3,Premium,1693,NaN,NaN,NaN,NaN,NaN,NaN,NaN
watch_hours,5000.0,NaN,NaN,NaN,11.64945,12.014654,0.01,3.3375,8.0,16.03,110.4
last_login_days,5000.0,NaN,NaN,NaN,30.0898,17.536078,0.0,15.0,30.0,45.0,60.0
region,5000,6,South America,873,NaN,NaN,NaN,NaN,NaN,NaN,NaN
device,5000,5,Tablet,1048,NaN,NaN,NaN,NaN,NaN,NaN,NaN
monthly_fee,5000.0,NaN,NaN,NaN,13.6834,3.692062,8.99,8.99,13.99,17.99,17.99
churned,5000.0,NaN,NaN,NaN,0.503,0.500041,0.0,0.0,1.0,1.0,1.0


In [36]:
df.isnull().sum()

customer_id               0
age                       0
gender                    0
subscription_type         0
watch_hours               0
last_login_days           0
region                    0
device                    0
monthly_fee               0
churned                   0
payment_method            0
number_of_profiles        0
avg_watch_time_per_day    0
favorite_genre            0
dtype: int64

In [39]:
df.isna().mean() * 100

customer_id               0.0
age                       0.0
gender                    0.0
subscription_type         0.0
watch_hours               0.0
last_login_days           0.0
region                    0.0
device                    0.0
monthly_fee               0.0
churned                   0.0
payment_method            0.0
number_of_profiles        0.0
avg_watch_time_per_day    0.0
favorite_genre            0.0
dtype: float64

In [40]:
df_drop=df.dropna()
print(df_drop.shape)

(5000, 14)


In [1]:
df.info()

NameError: name 'df' is not defined

In [10]:
#code to fill the missing numeric  values by mean
import pandas as pd
import mysql.connector;
from sqlalchemy import create_engine;
engine=create_engine('mysql+mysqlconnector://root:bca1234@localhost/shaikh');
query=("select * from movie1")
df=pd.read_sql(query,engine)
df['duration']=df['duration'].fillna(df['duration'].mean());
data = {
    "movie_name":["tarzan"],
    "movie_type":["null"],
    "director":["kjl"],
    "country":["london"],
    "title_id":["109"],
    "duration":["4"],
    "extra_field":["3.2"]
}
#code to fill the missing categorical  values by mode
df['movie_type']=df['movie_type'].fillna(df['movie_type'].mode()[0]);
#front fill
#df[‘subscription_type’].fillna(method='ffill', inplace=True)
#backword fill
#df['extra_field']=df['extra_field'].bfill()



In [5]:
#text preprocessing
df['movie_name']=df['movie_name'].str.lower().str.strip()
df['director'] = df['director'].replace(
    {'abc':'abraham benjamin stokes',
     'xyz':'xavier barlet',
     'lmn':'luhan de pretorious'
    })
#df[df['movie_name']=='roy'][['director','movie_type']].head();


NameError: name 'df' is not defined

In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print("Mean:", np.mean(arr))
print("Square each element:", arr ** 2)

Mean: 3.0
Square each element: [ 1  4  9 16 25]


In [3]:
matrix = np.array([[1], [2], [3]])
vector = np.array([10, 20, 30])
print(matrix + vector)

[[11 21 31]
 [12 22 32]
 [13 23 33]]
